carts/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('',views.cart,name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/',views.remove_cart,name='remove_cart'),
    path('remove_cart_item/<int:product_id>/',views.remove_cart_item,name='remove_cart_item'),
    path('chechout/',views.checkout,name="checkout")
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/',include('admin_honeypot.urls',namespace='admin_honeypot')),
    path('securelogin/', admin.site.urls),
    path('',views.home,name="home"),
    path('store/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('account/',include('account.urls')),
    path('order/',include('orders.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('',views.store,name='store'),
    path('category/<slug:categories_slug>',views.store,name='product_by_category'),
    path('category/<slug:categories_slug>/<slug:product_slug>/',views.product_detail,name='product_detail'),
    path('search',views.search,name='search'),
    path('submit_review/<int:product_id>/',views.submit_review,name="submit_review")
]

carts/models.py
from django.db import models
from store.models import Product
from account.models import Account
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    user=models.ForeignKey(Account, on_delete=models.CASCADE,null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE,null=True)
    quantity=models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return str(self.product)
    
    
        

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
from account.models import *
from django.db.models import Avg,Count

# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length = 150,unique=True)
    slug = models.SlugField(max_length = 150,unique=True)
    description = models.TextField(max_length=500,blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to='photo/product')
    stock = models.IntegerField()
    is_available=models.BooleanField(default=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)

    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def countreview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    
    def get_url(self):
        return reverse('product_detail',args=[self.category.slug,self.slug])

    def __str__(self):
        return self.product_name
    
class VariationManager(models.Manager):
    def colors(self):
        return self.filter(variation_category='color', is_activate=True)
        # return super(Variation,self).filter(variation_value='size',is_activate=True)

    
    def sizes(self):
        return self.filter(variation_category='size', is_activate=True)



class Variation(models.Model):
    variation_category_choice=(
        ('color','color'),
        ('size','size'),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length = 150,choices=variation_category_choice)
    variation_value = models.CharField(max_length = 150)
    is_activate = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now=True)

    objects=VariationManager()

    def __unicode__(self): # same as __str__(self) __unicode us for integer
        return self.product

    
    
    
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user=models.ForeignKey(Account,on_delete=models.CASCADE)
    subject = models.CharField(max_length = 100,blank=True)
    review=models.TextField(max_length=100)
    rating = models.FloatField()
    ip = models.CharField(max_length = 150)
    status=models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class ProductGallery(models.Model):
    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'  # Corrected attribute name


    def __str__(self):
        return self.product.product_name
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)


    
    
    

store/forms.py
from django import forms
from .models import ReviewRating

class ReviewForm(forms.ModelForm):
    class Meta:
        model=ReviewRating
        fields=["subject","review","rating"]

carts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from store.models import Product
from .models import *
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from orders.forms import *

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        if request.user.is_authenticated:
            cart=Cart.objects.get(cart_id=request.user.email)
        else:
            cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        if request.user.is_authenticated:
            cart=Cart.objects.create(cart_id=request.user.email)
        else:
            cart=Cart.objects.create(cart_id=_cart_id(request))
            cart.save()
    try:
        if request.user.is_authenticated:
            cart_item=CartItem.objects.get(product=product,user=request.user)
            cart_item.quantity+=1
            cart_item.save()
        else:
            cart_item=CartItem.objects.get(product=product,cart=cart)
            cart_item.quantity+=1
            cart_item.save()
   
    except CartItem.DoesNotExist:
            if request.user.is_authenticated:
                cart_item=CartItem.objects.create(product=product,quantity=1,user=request.user)
                cart_item.save()
            else:
                cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
                cart_item.save()

    return redirect('cart')


def remove_cart(request,product_id):
    product=get_object_or_404(Product,id=product_id)
    # cart_item=CartItem.objects.get(product=product,cart=cart)
    if request.user.is_authenticated:
        cart_item=CartItem.objects.get(product=product,user=request.user) 
    else:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_item=CartItem.objects.get(product=product,cart=cart)
    if  cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart')

def remove_cart_item(request,product_id):
    product=get_object_or_404(Product,id=product_id)
    if request.user.is_authenticated:
        cart_item=CartItem.objects.get(product=product,user=request.user)
    else:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart')
 
def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0  
        grand_total = 0 
        if request.user.is_authenticated:
            cart_items = CartItem.objects.all().filter(user=request.user)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
            pass
    context={
        'total':total,
        'quantity':quantity,
        'cart_items':cart_items,
        'tax':tax,
        'grand_total':grand_total

    }


    return render(request, "store/cart.html", context)

@login_required(login_url='login')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0  
        grand_total = 0 
        if request.user.is_authenticated:
            cart_items = CartItem.objects.all().filter(user=request.user)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        
        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass
    form=OrderForm()  
    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
        'form':form
    }
    
    return render(request, "store/checkout.html",context)   

greatkart/views.py
from django.shortcuts import render
from store.models import Product
from store.models import ReviewRating
def home(request):
    products = Product.objects.all().filter(is_available=True).order_by('-created_date')
    reviews_dict = {}  # Create an empty dictionary to store reviews for each product

    for product in products:
        try:
            reviews = ReviewRating.objects.filter(product=product, status=True)
            reviews_dict[product.id] = reviews  # Store reviews in the dictionary with product IDs as keys
        except ReviewRating.DoesNotExist:
            reviews_dict[product.id] = []  # Handle the case when no reviews are found for a product

    context = {
        'products': products,
        'reviews_dict': reviews_dict  # Pass the dictionary containing reviews to the template
    }

    return render(request, 'home.html', context)

store/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Product,ReviewRating,ProductGallery
from category.models import Category
from carts.models import *
from carts.views import _cart_id
from django.http import HttpResponse 
from django.db.models import Q 
from django.contrib import messages,auth
from orders.models import OrderProduct


from .forms import ReviewForm

# Create your views here.

def store(request,categories_slug=None):
    categories=None
    products=None
    if categories_slug!=None:
        categories=get_object_or_404(Category,slug=categories_slug)
        products=Product.objects.filter(category=categories,is_available=True)
    else:    
        products=Product.objects.all().filter(is_available=True)
    
    context={
        'products':products,
        'products_count':products.count()
    }
    
    return render(request,'store/store.html',context)

def product_detail(request,categories_slug,product_slug):

    try:
        category = Category.objects.get(slug=categories_slug)
        single_product = Product.objects.get(category=category, slug=product_slug)
        in_cart=CartItem.objects.filter(cart__cart_id=_cart_id(request)).exists()
    except Exception as e:
        raise e
    
    try:
        orderproduct=OrderProduct.objects.filter(user=request.user,product=single_product).exists()
    except:
        orderproduct=None
    # Get review
    reviews=ReviewRating.objects.filter(product=single_product,status=True) 
    product_gallery=ProductGallery.objects.filter(product=single_product)
    context={
        'single_product':single_product,
        'in_cart':in_cart,
        'orderproduct':orderproduct,
        'reviews':reviews,
        'product_gallery':product_gallery
    }
    return render(request,'store/product_detail.html',context)

def search(request):
    if 'keywords' in request.GET:
        keyword = request.GET['keywords']
        if keyword:
            products=Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))         

    context={
    'products':products,
    'products_count':products.count()
    }
    return render(request,'store/store.html',context)



def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=product_id)
    print("user:-",request.user.id)
    if request.method == "POST":
        try:
            review = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            print("review:-",review)
            form = ReviewForm(request.POST, instance=review)
            form.save()
            messages.success(request, "Thank you! Your review has been updated.")
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                # data = form.save(commit=False) or
                data=ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product = product
                data.user = request.user
                data.save()
                messages.success(request, "Thank you! Your review has been submitted.")
            return redirect(url)

greatkart/templates/store/cart.html
{% extends 'base.html' %}


{% block content %}
{% load static %}
<section class="section-content padding-y bg">
    <div class="container">
    {% if not cart_items %}
    <h2 class="text-center text-danger">Your Shopping Cart is Empty</h2>
    <br>
    <div class="text-center">
        <a href="{% url 'store' %}" class="btn btn-success">Continue Shopping</a>
    </div>
    {% else %}
    <!-- ============================ COMPONENT 1 ================================= -->
    
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
        {% for cart_item in cart_items %}
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                <figcaption class="info">
                    <a href="{{  cart_item.product.get_url  }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                    <p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <a href="{% url 'remove_cart' cart_item.product.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                </div>
                                <input type="text" class="form-control"  value="{{ cart_item.quantity }}">
                                <div class="input-group-append">
                                <a href="{% url 'add_cart' cart_item.product.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </a>
                                </div>
                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">${{ cart_item.sub_total }}</var> 
                <small class="text-muted"> ${{ cart_item.product.price }} each </small> 
             
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
        <a href="{% url 'remove_cart_item' cart_item.product.id %}" class="btn btn-danger"> Remove</a>
        </td>
    </tr>
    {% endfor %}

    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{ total }}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{ tax }}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{ grand_total }}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static 'images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
   {% endif %}
    </div> <!-- container .//  -->
    </section>
{% endblock %}

greatkart/templates/store/product_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
  /* Hide Radio button */
.rate > input{
    display: none;
}

.rate{
    display: inline-block;
    border: 0;
   
}

.rate > label{
    float: right;
}

/* Showing the stars */
 
.rate > label:before{
    display: inline-block;
    font-size: 1.1rem;
    font-family: FontAwesome;
    content: "\f005";
    margin: 0;
    padding: 0.3rem .2rem;
    cursor: pointer;
}  

/* half star */

/* .rate .half:before{
    content: "\f098";
    position: absolute;
    padding-right: 0;
} */

input:checked ~ label, label:hover ~ label{
    color: #ffb503;
}

input:checked + label:hover, input:checked ~ label:hover, input:checked~label:hover~label,label:hover~input:checked~label{
  color: #cc9000;
}

.reting-star i{
  color: #ffb503 !important;
}

ul.thumb{
  margin: 0 auto;
  padding: 0;
  float: left;
}

ul.thumb li{
  list-style: none;
  margin: 10px;
}

ul.thumb li img{
  width: 80px;
  height: 80px;
  border: 1px solid gray;
}
</style>
<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters">
        <aside class="col-md-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap mainImage">
             <center><img src="{{ single_product.images.url }}"></center> 
            </div> <!-- img-big-wrap.// -->

          </article> <!-- gallery-wrap .end// -->
          <ul class="thumb">
            <li>
              <a href="{{ single_product.images.url }}" target="mainImage"><img src="{{ single_product.images.url }}" alt="Product Image"></a>

              {% for i in product_gallery %}
             
              <a href="{{ i.image.url }}" target="mainImage"><img src="{{ i.image.url }}" alt="Product Image"></a>
              {% endfor %}
            </li>
          </ul>
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add_cart' single_product.id %}">
            {% csrf_token %}
       
          <article class="content-body">

            <h2 class="title">{{ single_product.product_name }}</h2>
            <div class="reting-star">
              <span>
                  <h6 class="mb-1">{{ review.user.fullname }}</h6>
                  <i class="fa fa-star{% if single_product.averageReview < 0 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 1 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 2 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 3 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 4 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 5 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 6 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 7 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 8 %}-o {% endif %}" aria-hidden="true"></i>
                  <i class="fa fa-star{% if single_product.averageReview < 9 %}-o {% endif %}" aria-hidden="true"></i>
                     
                </span>
              </div>
              <span>{{ single_product.countreview }} reviews</span>
            <div class="mb-3">
              <var class="price h4">${{single_product.price }}</var>
            </div>

            <p>{{ single_product.description }}.</p>


            <hr>
            <div class="row">
              <div class="item-option-select">
                <h6>Choose Color</h6>
                <select name="color" class="form-control" required>
                  <option value="" disabled selected>Choose Color</option>
                  {% for item in single_product.variation_set.colors %}
                  <option value="{{ item.variation_value | lower }}">{{ item.variation_value | capfirst }}</option>
                  {% endfor %}
                </select>
              </div>
            </div> <!-- row.// -->
            <div class="row">
              <div class="item-option-select">
                <h6>Select Size</h6>
                <select name="size" class="form-control" required>
                  <option value="" disabled selected>Choose Size</option>
                  {% for item in single_product.variation_set.sizes %}
                  <option value="{{ item.variation_value | lower }}">{{ item.variation_value | capfirst }}</option>
                  {% endfor %}
                </select>
              </div>
            </div> <!-- row.// -->
            <hr>
            {% if single_product.stock %}
            {% if in_cart %}
            <a href="#" class="btn  btn-success"> <span class="text">Add to cart</span> <i class="fas fa-check"></i>
            </a>
            <a href="{% url 'cart' %}" class="btn  btn-outline-primary"> <span class="text">View cart</span> <i
                class="fas fa-eye"></i> </a>
            {% else %}
            <a href="{% url 'add_cart' single_product.id %}" type="submit" class="btn  btn-primary"> <span class="text">Add to
                cart</span> <i class="fas fa-shopping-cart"></i> </a>
            {% endif %}
            {% else %}
            <h5 class="text-danger">Out of Stock</h5>
            {% endif %}
          </article> <!-- product-info-aside .// -->
        </form>
        </main> <!-- col.// -->
      </div> <!-- row.// -->
    </div> <!-- card.// -->


    <br>

    <div class="row">
      <div class="col-md-9">


   
        <form action="{% url 'submit_review' single_product.id %}" method="post">
          {% csrf_token %}
          <h5>Write Your review</h5>
          {{ single_product.averageReview }}
          <div>
            <label for="">How do you rate this product ?</label>
            <br>
           
            <div class="rate">
              <input type="radio" name="rating" id="rating10" value="10"  required><label for="rating10" title="10"></label>
              <input type="radio" name="rating" id="rating9" value="9" required><label for="rating9" title="9" class="half"></label>
              <input type="radio" name="rating" id="rating8" value="8" required><label for="rating8" title="8"></label>
              <input type="radio" name="rating" id="rating7" value="7" required><label for="rating7" title="7" class="half"></label>
              <input type="radio" name="rating" id="rating6" value="6" required><label for="rating6" title="6"></label>
              <input type="radio" name="rating" id="rating5" value="5" required><label for="rating5" title="5" class="half"></label>
              <input type="radio" name="rating" id="rating4" value="4" required><label for="rating4" title="4"></label>
              <input type="radio" name="rating" id="rating3" value="3" required><label for="rating13" title="3" class="half"></label>
              <input type="radio" name="rating" id="rating2" value="2" required><label for="rating2" title="2"></label>
              <input type="radio" name="rating" id="rating1" value="1" required><label for="rating1" title="1" class="half"></label>

            </div>
         <br>
              Review Title 
              <input type="text" class="form-control" name="subject" required>
              <br>
              Review:
              <textarea name="review" id="" class="form-control" rows="4" required></textarea>
              <br>
              {% if user.is_authenticated %}
              {% if orderproduct %}
              <input type="submit" value="Submit Review" class="btn btn-primary">
              {% else %}
              <p>You must be purchase this product to post a review.</p>
              {% endif %}
            {% else %}
              <P>you must logged in to post a review.<span><a href="{% url 'login' %}">Login Now.</a></span></P>
            {% endif %}
          </div>
          {% include 'include/alert-massage.html' %}
        </form>
        <br>
        <header class="section-heading">
          <h3>Customer Reviews </h3>
          <div class="reting-star">
          <span>
              <h6 class="mb-1">{{ review.user.fullname }}</h6>
              <i class="fa fa-star{% if single_product.averageReview < 0 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 1 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 2 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 3 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 4 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 5 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 6 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 7 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 8 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if single_product.averageReview < 9 %}-o {% endif %}" aria-hidden="true"></i>
              <span>{{ single_product.countreview }} reviews</span>
            </span>
          </div>
        </header>
        {% for review in reviews %}
        <article class="box mb-3">
          <div class="icontext w-100">
            <div class="text">
              <!-- <img src="{% static 'images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle"> -->
              <span class="date text-muted float-md-right">{{ review.updated_date }} </span>
            <div class="reting-star">
              <h6 class="mb-1">{{ review.user.fullname }}</h6>
              <i class="fa fa-star{% if review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review.rating < 6 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review.rating < 7 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review.rating < 8 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review.rating < 9 %}-o {% endif %}" aria-hidden="true"></i>
              <i class="fa fa-star{% if review.rating < 10 %}-o {% endif %}" aria-hidden="true"></i>
             
            </div>
          </div>
          </div> <!-- icontext.// -->
          <div class="mt-3">
            <h6>{{ review.subject }}</h6>
            <p>
              {{ review.review }}
            </p>
          </div>
        </article>
{% endfor %}


      </div> <!-- col.// -->
    </div> <!-- row.// -->


  </div> <!-- container .//  -->
</section>
{% endblock %}